### ISSUE TITLE
Timeout when adding a specific instance

### ISSUE THREAD

**Issue by PetraOleum** [NicolasConstant/sengi#332] opened 2020-11-18 03:00 UTC
Trying to add `cloudisland.nz` gives an (immediate) 504 gateway timeout on both the appimage and web version, however the instance admin [says she sees the POST requests fine](https://cloudisland.nz/@PetraOleum/105228996856590788). Is there a way to get sengi's own logs and see what's going on? This also seems to be the error the UI gives when you give it a url that ought to 404 rather than 504, but that shouldn't be the issue here.

**Comment by NicolasConstant** [comment] 2020-11-18 07:21
Hello! 
Sorry you ran into this issue. I can reproduce the bug and my guess is that it's a CORS issue. I'm pretty sure your admin don't let the instance's API to be acceded from another website/domain name (i.e. "access-control-allow-origin: *").

You can see you have the same issue from other alternative front-ends like [Pinafore](https://pinafore.social/) with this instance.

Your administrator have to set the instance ```Access-Control-Allow-Origin``` header to ```*``` (to work with all alternatives front-ends), or at least ```https://sengi.nicolas-constant.com``` (to work with Sengi).

**Comment by kstrauser** [comment] 2020-11-24 19:37
I'm having the same problem when downloading and running Sengi locally. CORS shouldn't be an issue there, should it?

**Comment by NicolasConstant** [comment] 2020-11-24 21:50
How are you running it locally? via docker?

**Comment by kstrauser** [comment] 2020-11-24 22:41
Via downloading the Mac app and running it.

**Comment by NicolasConstant** [comment] 2020-11-24 22:54
Oh I see, unfortunately the Electron build is only a wrapper of the online version (the app is served and updated via the `https://sengi.nicolas-constant.com` URL) so the CORS issue will still be here. 😕
The only build I provide that is really served locally is the docker one.

**Comment by kstrauser** [comment] 2020-11-24 23:01
Ah, got it. On further digging, I'm surprised because the instance I'm trying to use (at https://freeradical.zone/) has that header set.

**Comment by NicolasConstant** [comment] 2020-11-25 05:29
I've looked to `https://freeradical.zone` in its case there is _too much_ headers set. 😬
![image](https://user-images.githubusercontent.com/5437247/100186723-8c6ee180-2eb4-11eb-87b8-e8de22580833.png)
I guess something on this instance is duplicating some headers... If your administrator is googling this message with the instance stack they should be able to fix it. 🙂

I'm sorry for the hassle it brings, but unfortunately this is an instance issue fighting with browser's security (in fact, the app itself is unaware of what's going on), and therefore I can't do anything on my side.

**Comment by muojik** [comment] 2020-12-26 02:25
If you use the webapp, one solution is to install the extension: [https://mybrowseraddon.com/access-control-allow-origin.html](https://mybrowseraddon.com/access-control-allow-origin.html) . (for chrome, firefox, edge and opera). 
I use it in chrome, and I can restrict access to only sengi's webapp.

**Comment by NicolasConstant** [comment] 2021-01-04 07:24
I'm closing since this is not really related to Sengi but mostly a CORS issue in the browsers.

**Closed by NicolasConstant** 2021-01-04 07:24 UTC

**Comment by tfardet** [comment] 2022-07-18 06:05
@NicolasConstant sorry for reviving this old issue, but I'm encountering the same problem on https://toot.aquilenet.fr but the site seems to have the "access-control-allow-origin" header set to "*"... Could you  please check whether this is indeed unrelated or if the header might be missing only on some specific route that makes it problematic for Sengi?

**Comment by NicolasConstant** [comment] 2022-07-18 06:14
@tfardet same issue: 
![image](https://user-images.githubusercontent.com/5437247/179454039-7a38d435-608c-4e2f-a1f4-f41ccaf76d2b.png)

This header shouldn't return multiple value, if it does most browser will reject it by design, and it's not related in any way to Sengi.

**Comment by tfardet** [comment] 2022-07-18 12:31
OK, I'll transmit that, thanks! Out of curiosity, how do you get that result? Using the Firefox developer tools on the website does not seem to give the same result.

**Comment by NicolasConstant** [comment] 2022-07-18 16:07
Chrome seems to be move verbose indeed, it's strange Firefox don't notify more explicitly this issue.

**Comment by tfardet** [comment] 2022-07-20 17:14
So they told me they corrected it (duplicate between normal and mozilla CSP apparently).
Checking with Chrome and curl, it seems fine but sengi still does not accept the connection (though the error message changed, speaking about CORS, but I expect that's something you did?)

cURL command and response:

```
curl -v POST
        -F 'client_name=Test Application' \
        -F 'redirect_uris=urn:ietf:wg:oauth:2.0:oob' \
        -F 'scopes=read write follow' \
        https://toot.aquilenet.fr/api/v1/apps
* Connected to toot.aquilenet.fr port 443
[...]
* We are completely uploaded and fine
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< date: Wed, 20 Jul 2022 17:07:58 GMT
< content-type: application/json; charset=utf-8
< server: Mastodon
[...]
< access-control-allow-origin: *
< content-security-policy: default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; img-src 'self' blob: data:; connect-src 'self' blob: wss://toot.aquilenet.fr;
< 
* Connection #0 to host toot.aquilenet.fr left intact
{json content}%
```

Any idea what's wrong? Could it be some local caching issue?

**Comment by tfardet** [comment] 2022-07-20 18:58
Thanks for checking again.
Could you tell me precisely how to reproduce this result from my computer so I can dig deeper a bit?
In particular, do you understand why you/Sengi get different results from cURL (which says the CORS is valid)?

Alternatively, is there any way to heed the error message's advice on the last line and add the "no-cors"' to the request?

**Comment by NicolasConstant** [comment] 2022-07-20 19:36
CORS is mostly a web thing (so has a impact when accessed from a browser), and I'm using the Chrome console to output the images I'm sharing here.

The no-cors isn't really a solution ([see here why](https://stackoverflow.com/questions/43262121/trying-to-use-fetch-and-pass-in-mode-no-cors)), in fact, there isn't anything I can do on Sengi (the webapp) side to fix it, even detecting it isn't really reliable and leads to some false positives. 

What could work would be using a CORS-proxy: an API correctly set on the CORS aspect that would call after that the original API (here the instance API). But there is an issue doing that: first it would need to host another resource (maintenance/cost/etc) and also a privacy issue, since all the calls would go through it, the owner of the proxy could theoretically access all your data / authentication token / etc.

**Comment by tfardet** [comment] 2022-07-20 20:36
I understand.
But could you let me know which page/tool you testing with Chrome?

Using the developper tools and checking the network tab on Chromium gives me this on the main page (toot.aquilenet.fr, which redirects to the about page):
![chromium network tab shows header correctly marked as "access-control-allow-origin: *"](https://user-images.githubusercontent.com/79037344/180076465-88fb1dcd-6f72-4b56-b5fb-70316b4c3594.png)
And this on the console:
![Only error in console is "Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'."](https://user-images.githubusercontent.com/79037344/180076635-77e7293c-0ffa-42fc-a7e1-8675649fc9f0.png)

**Comment by NicolasConstant** [comment] 2022-07-20 20:39
Oh ok, just try to add a new account, on the "Submit" action after providing your instance it will display the error (in the console).
