### ISSUE TITLE
Honour "Auto-play animated GIFs" setting from the web

### ISSUE THREAD

**Issue by GrahamDo** [NicolasConstant/sengi#578] opened 2023-05-15 05:28 UTC
I really really dislike it when animated gifs play automatically in my timeline. Which is why I disabled it in my settings on the web. Please can Sengi honour that setting? (Or at least have its own version of that setting)

**Comment by NicolasConstant** [comment] 2023-05-18 23:23
duplicate of #555

**Closed by NicolasConstant** 2023-05-18 23:23 UTC
