### ISSUE TITLE
Opening Reply threads broken on Pleroma release 2.3.0

### ISSUE THREAD

**Issue by Salastil** [NicolasConstant/sengi#360] opened 2021-03-07 02:44 UTC
When opening a status to see the replies the column shows the loading indicator before finally timing out with an error stating "could not find status"
![1615084299](https://user-images.githubusercontent.com/46979341/110227191-bf693e00-7ec3-11eb-8824-e5304087af57.png)
The only change is that the account instance is running on Pleroma 2.3.0 : https://pleroma.social/announcements/2021/03/02/pleroma-major-release-2-3-0/ When I switch to a different account running 2.2.2 and try entering the same threads it will load as expected. I can issue fresh status without issue and even reply to threads I loaded with the account on a Pleroma 2.2.2 instance.

**Comment by NicolasConstant** [comment] 2021-03-08 01:19
I successfully reproduced the issue, it's a 2.3.0 API regression, I've opened an issue on Pleroma's repo: https://git.pleroma.social/pleroma/pleroma/-/issues/2566

**Comment by lanodan** [comment] 2021-04-15 21:19
Without dismishing that search is broken in 2.3.0, I feel like this is a misuse of MastodonAPI, why are you using search for seeing replies when you should already have everything needed to use the context endpoint?

**Comment by NicolasConstant** [comment] 2021-04-15 21:24
Because of the multi-users functionalities of Sengi: opening/faving/boosting/etc a status (retrieved and displayed from one account/instance) will not be available with the same ID for another account/instance, searching it ensure having the local view for the currently selected user.

**Comment by Ashdemai** [comment] 2021-05-18 18:43
It sucks that this problem still have no solution, I would love to use Sengi more, but this is way too annoying.

**Comment by Ashdemai** [comment] 2021-08-10 11:39
Since Pleroma updated to version 2.4.0 do anyone see the issue continuing or being able to be fixed at the least?

**Comment by NicolasConstant** [comment] 2021-08-11 00:23
Just tried it, still broken, reverting my instance to 2.2.0.

**Comment by Salastil** [comment] 2021-08-11 03:31
Considering this bug is nearly 4 months old, and it would appear that Pleroma has slowed down to just a few developers -- none of whom seem interested in correcting the search issues in the near term, would it be prudent to consider giving up on the multi-user functionality (cross posting, repeats etc) and go with the route lanodan talked about above? With the pending removal of glitch-soc as a packaged option there will be no multi-column front ends functional with a Pleroma instance launched in 2021 (there was an explosion of growth in 2021 because of Twitter banwaves) given that 2.2.1 was a Dec 2020 release.

**Comment by NicolasConstant** [comment] 2021-08-11 03:48
I'm considering indeed to add the optimization that if you're using the account of the given TL, I'll directly use the given ID, the issue is that this modification will impact a huge part of the code, it will take some time, it's not a little fix (that was mainly why I was reluctant to do this optimization/fix in the first place).

But it won't solve the multi-user functionality, so Sengi will still be broken on this part. 

And even on single-user use cases, it will fails on the `remote` statuses functionalities: remote status are the one that aren't synchronized with your instance, but that I'm fetching directly from the original's instance of the author of the thread, those also are resolved on fav/boost/reply/etc. 

Sengi is offering a lot though the search functionality.

**Comment by ioistired** [comment] 2021-08-12 07:15
> and it would appear that Pleroma has slowed down to just a few developers

It sped up a lot now that they have the infamous TERF Alex Gleason on board as a core dev :hidethepain:

They also just added a milestone of 2.4.1 to this issue: https://git.pleroma.social/pleroma/pleroma/-/issues/2566

**Comment by ioistired** [comment] 2021-08-17 06:45
OK acknowledged

**Comment by Ashdemai** [comment] 2021-08-30 10:42
Issue seems fixed in version 2.4.1

It's working as intended again.

**Comment by NicolasConstant** [comment] 2021-08-31 02:58
That's great! Huge thanks to @lanodan for fixing it!

**Closed by NicolasConstant** 2021-08-31 02:58 UTC
Labels: bug
