### ISSUE TITLE
Pixelfed posts not rendering properly

### ISSUE THREAD

**Issue by rpetti** [NicolasConstant/sengi#577] opened 2023-05-06 19:36 UTC
Started noticing this while following `#mastoart`. It seems some posts from pixelfed instances aren't rendering properly.

Here's an example:
https://pix.anduin.net/p/Vision-Logic/560525181694837214
![image](https://user-images.githubusercontent.com/207173/236643348-021f3972-6c85-4112-9077-43fd6d15683f.png)

It renders properly in the instance's UI, but not Sengi.

**Comment by NicolasConstant** [comment] 2023-05-14 18:34
duplicate of #524 
(will try to fix that in next release 🙂)

**Closed by NicolasConstant** 2023-05-14 18:34 UTC
