### ISSUE TITLE
Sengi preventing screensaver / sleep

### ISSUE THREAD

**Issue by dangbunni** [NicolasConstant/sengi#617] opened 2023-09-01 17:50 UTC
Manjaro Linux, xfce desktop, Sengi 1.6.0 installed from Add/Remove Software sengi-bin package

Screensavers will not come on and monitors will not sleep while Sengi is running. Power Management reports four instances of "/usr/lib/electron32/electron is currently inhibiting power management"

Other Electron apps (Discord, etc) do not cause this.

If I uninstall sengi-bin and instead use sengi-appimage I get four instances of "/tmp/.mount_sengin9hkjw/sengi is currently inhibiting power management"

Manually suspending the monitors with "sleep 2;xset dpms force off" puts the monitors to sleep then they immediately wake back up.

In either case, closing Sengi clears the issue.

**Comment by NicolasConstant** [comment] 2023-09-05 22:20
duplicate of #492

**Closed by NicolasConstant** 2023-09-05 22:20 UTC
