### ISSUE TITLE
[Feature Request]: Local timeline view of third party instance

### ISSUE THREAD

**Issue by anantshri** [NicolasConstant/sengi#488] opened 2022-11-23 06:58 UTC
Most fediverse servers especially mastodon instances keep local feeds public. Is it possible to give user a chance to enter the instance name and we get a column added which has local feed of that instance displayed to us.

Couple of usecases.

1. I have my id in a different instance but suddenly have curiosity about another topic which is relevent for different groups instead of creating another login i would prefer to observe first.
2. I self host so i have my own instance for interaction i would prefer finding like minded folks on other instances instead of hunting for good connections all the time I can observe the local feed and see how i can interact.

As of now, this is possible if i create a account on that instance and enable it in interface then show local timeline but would love if we can do it without having an id on other instance.

**Comment by NicolasConstant** [comment] 2022-11-23 19:25
duplicate of #476

**Closed by NicolasConstant** 2022-11-23 19:25 UTC
Labels: duplicate
