### ISSUE TITLE
[Feature Request] Filter by keyword of phrase

### ISSUE THREAD

**Issue by erik-sk** [NicolasConstant/sengi#533] opened 2022-12-21 09:01 UTC
It would be nice if filters made in the account web interface worked in the app. Or if it would just be possible to add filters in the app. 

It hadn't really been an issue until a barrage of spam came through my main account and I noticed filters I made in the web interface were not blocking things in the app.

**Comment by NicolasConstant** [comment] 2022-12-21 22:18
duplicate of #414

**Closed by NicolasConstant** 2022-12-21 22:18 UTC
