### ISSUE TITLE
FEATURE REQUEST: Make it obvious which account you are posting under

### ISSUE THREAD

**Issue by MrEnigmaSr** [NicolasConstant/sengi#528] opened 2022-12-20 12:23 UTC
It might sound counter-intuitive to say this but it is TOO easy to manage multiple accounts.  Its very easy to accidentally cross-post.  This could probably just be resolved with a little ui work- a theme could highlight/animate the avatar of the account you are currently using... and when you go to write or retoot it could show the account you are currently using to make sure you don't absent-mindedly tit instead of toot.

**Comment by NicolasConstant** [comment] 2022-12-20 22:03
duplicate of #477 and possibly #491 too

**Closed by NicolasConstant** 2022-12-20 22:03 UTC
