### ISSUE TITLE
When clicking the Search button, set focus to the Search textbox

### ISSUE THREAD

**Issue by GrahamDo** [NicolasConstant/sengi#543] opened 2022-12-30 14:42 UTC
Too often have I clicked the little magnifying glass and then started typing, but it's tried to add an account because I typed "a".

It would be helpful if Sengi automatically set the focus to the textbox immediately after I click that button. :-)

**Comment by NicolasConstant** [comment] 2022-12-30 20:48
duplicate of #429

**Closed by NicolasConstant** 2022-12-30 20:48 UTC
Labels: duplicate
