### ISSUE TITLE
Feature Request: Multiple hashtags per column

### ISSUE THREAD

**Issue by mttaggart** [NicolasConstant/sengi#428] opened 2022-04-28 15:28 UTC
Hi there! First, thank you so much for this awesome app. Really appreciate the fantastic work.

One shortcoming I've observed is the inability to add multiple hashtags to a pinned column, as in the web app. 

![image](https://user-images.githubusercontent.com/6811816/165788489-9b18af05-55fe-48fa-b35b-0b3b91c66019.png)

Perhaps this _is_ possible and I've just missed it, but if not, it would be a phenomenal functionality add.

Thanks again!

**Comment by NicolasConstant** [comment] 2022-04-29 00:55
It's not supported right now, and it would be a cool feature indeed!

(I'm closing this issue since it's a duplicate of #333)

**Closed by NicolasConstant** 2022-04-29 00:55 UTC
Labels: duplicate
