### ISSUE TITLE
Adjust font, size etc

### ISSUE THREAD

**Issue by audunmb** [NicolasConstant/sengi#463] opened 2022-11-10 08:36 UTC
I find the text a bit small to read. An option to adjust font, line height, font size etc would be nice.

**Comment by NicolasConstant** [comment] 2022-11-13 21:45
duplicate of #222 
(but you can also zoom in/out in the Electron build or in the browser if you want)

**Closed by NicolasConstant** 2022-11-13 21:45 UTC

**Comment by ejheil** [comment] 2022-11-20 08:29
@NicolasConstant  as noted in #222 the option to increase font size does not exist in the "view" menu of the Mac build.  Is there a workaround?

**Comment by NicolasConstant** [comment] 2022-11-20 11:58
You could use the web version, but I'll have a look (when finding the time) why this option doesn't show up on Mac.

Also, please participate on the other issue since this one is a duplicate.
