### ISSUE TITLE
Auto Column Width

### ISSUE THREAD

**Issue by Ovadex** [NicolasConstant/sengi#514] opened 2022-12-08 07:27 UTC
It would be very nice for the columns to fill the window with with a max and min column width. 
That way they don't get too wide but also don't end up with columns half cut off on the side. Once the lower width limit is hit the whole last column pops off to the side completely rather than being cut in half.

**Comment by NicolasConstant** [comment] 2022-12-11 03:28
duplicate of #205

**Closed by NicolasConstant** 2022-12-11 03:28 UTC
