### ISSUE TITLE
Feature request / Possibility to follow multiple hashtags in one column

### ISSUE THREAD

**Issue by M0IGA** [NicolasConstant/sengi#432] opened 2022-05-03 06:35 UTC
When I'm clicking on a hashtag and opening a new column with it I would like to have the possibility to add more hashtags to this column like the web client has.

**Comment by NicolasConstant** [comment] 2022-05-03 22:08
Hi! It would be nice indeed! 

(I'm closing this issue since it's a duplicate of #333)

**Closed by NicolasConstant** 2022-05-03 22:08 UTC
Labels: duplicate
