### ISSUE TITLE
Feature request: available light & dark theme

### ISSUE THREAD

**Issue by iamdtms** [NicolasConstant/sengi#497] opened 2022-11-25 18:22 UTC
I use https://github.com/AutoDarkMode/Windows-Auto-Night-Mode app on desktop.
Interested in using the feature in sengi: available light & dark theme would be nice to have, switching can be solved by the OS, 
app only need to have @prefers-color-scheme implementations: https://web.dev/prefers-color-scheme/
I know it is a hard issue, but makes the app really user frendly that way. Thanks in advance.

**Comment by asmaloney** [comment] 2022-11-26 02:15
Duplicate of #396?

**Closed** 2022-11-26 17:23 UTC
Labels: duplicate
