### ISSUE TITLE
Ability to resize columns by px via settings

### ISSUE THREAD

**Issue by CliffWade** [NicolasConstant/sengi#557] opened 2023-01-27 22:44 UTC
Like others, I was using TweetDeck and/or Tweeten, and within the settings you could set the width by px for the columns. For example, you could set it to 300px and each column you had would be 300px wide. This allows you to have empty space or to perfectly fill the screen you completely if you want.

**Comment by NicolasConstant** [comment] 2023-01-28 07:52
duplicate of #460 and maybe #205 too

**Closed by NicolasConstant** 2023-01-28 07:52 UTC
